name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ test-branch ]
  pull_request:
    branches: [ test-branch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      name: Check out current branch
      with:
        path: local

    - name: Checkout next branch
      uses: actions/checkout@v2
      with:
        ref: test-branch
        path: test

    - name: Run test script
      run: |
        output=$(python local/helloworld.py local/*.md)
        echo "::set-output name=test_output::$output"
      id: test
        
    - name: print output
      run: |
        echo This is the output:
        echo "${{ steps.test.outputs.test_output }}"
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.3
    - name: test
      run: |
          echo '${{ steps.file_changes.outputs.files[0]}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_removed}}'
